import { GetStaticProps, type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import PokemonList from "../components/PokemonList";

const URL = "https://pokeapi.co/api/v2/pokemon?limit=5";

const Home: NextPage = ({ pokemon }: any) => {
  console.log(pokemon);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-content-center">
        <h1>Pokemon List</h1>
        {pokemon.map(({ name }: any, index: number) => {
          return (
            <div key={index}>
              <p>{name}</p>
            </div>
          );
        })}
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(URL);
  const { results } = await res.json();
  const pokemon = results.map((pokeman: any, index: any) => {
    const paddedId = ("00" + (index + 1)).slice(-3);
    const image = `https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${paddedId}.png`;
    return { ...pokeman, image };
  });
  return {
    props: { pokemon },
  };
};

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard: React.FC<TechnologyCardProps> = ({
  name,
  description,
  documentation,
}) => {
  return (
    <section className="flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <Link
        className="m-auto mt-3 w-fit text-sm text-violet-500 underline decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </Link>
    </section>
  );
};
